# Generated by Django 5.0.14 on 2026-06-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Processing', 'Processing'), ('Payment', 'Payment'), ('Confirmed', 'Confirmed'), ('Packing', 'Packing'), ('Packed', 'Packed'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='store.order')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'ordering': ['timestamp'],
            },
        ),
    ]
